% Auto-generated by cameraCalibrator app on 24-Dec-2018
%-------------------------------------------------------


% Define images to process
imageFileNames = {'E:\MATLAB_workplace\cv\project\calib1.jpg',...
    'E:\MATLAB_workplace\cv\project\calib2.jpg',...
    'E:\MATLAB_workplace\cv\project\calib3.jpg',...
    'E:\MATLAB_workplace\cv\project\calib4.jpg',...
    'E:\MATLAB_workplace\cv\project\calib5.jpg',...
    'E:\MATLAB_workplace\cv\project\calib6.jpg',...
    'E:\MATLAB_workplace\cv\project\calib7.jpg',...
    'E:\MATLAB_workplace\cv\project\calib8.jpg',...
    'E:\MATLAB_workplace\cv\project\calib9.jpg',...
    'E:\MATLAB_workplace\cv\project\calib10.jpg',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 30;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams, 'BarGraph');

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
originalImage = imread(imageFileNames{1});
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
